### ISSUE TITLE
Photocell sensor data for height measurement?

### ISSUE THREAD

**Issue by TokenChingy** [zaren171/RepliShot#1]
Quick question, the IR sensor data for back and front arrays, is that data exposed? My understanding of this is that the Optishot 2 is using photocells which would mean that it's measuring light intensity.

Given that light intensity and distance has a direct correlation, one could calculate the relative height change of the the back and front to work out angle of attack.

Is this possible?

**Comment by zaren171** [comment]
Oh that it were.  I was actually just thinking about that the other day, but the data that is presented over the USB interface does NOT include the intensity, just which sensors are "seeing" something.  I'll admit I had to reverse engineer the data format, and so I might have gotten it wrong, but it seems that triggered sensors and time delays are all that is transmitted in the data.
