### ISSUE TITLE
[Questions] which "the golf club 2019"? Contact?

### ISSUE THREAD

**Issue by ERamseth** [zaren171/RepliShot#5]
Hi- wasn't sure the best way to contact with questions...

Is this meant to work with TGC2019 that you can get from steam for 49$? Or the 895$ one from skytrak?

Also, on general, how well is this working?

Looking to take a plunge on making sure my OS2 works offline with the pending deactivation. Trying to decide if this setup is a good idea or if I should get the offline pro pass...

**Comment by zaren171** [comment]
Hello.  This is meant to work with the steam version of TGC2019.  It takes the data from the Optishot and converts it into keyboard and mouse inputs to drive the video game.  As for how well it's working, I'll first say I recommend running tgc2019 at 1920x1080 for use with this program.  In terms of accuracy, well, there's only so much data available from the OS2, and the video game has granularity to the power of swings, so it's not feasible to get an exact carry, but it should produce results in the correct range.  That said, I'd love to hear your feedback on how you feel it works.  There's also an "Arcade Multiplier" available, so if you feel your shots are always coming up a little long/short you can add an adjustment for that.

**Comment by ERamseth** [comment]
All of that aounds pretty good. And basically what i came to understand after reading the readme a little closer... actually i noticed the readme links to the steam version of tgc2019 too... so sorry for missing that. Fwiw 1080p is just fine for me. My stuff is connected to a projector that does something like 1080p.

I'll reply here because I don't know how to send some sort of inbox message on github (is that even a thing?)

Kinda wandering into a weird territory here but... subjectively, do you think the way tgc2019 reacts to replishot is on par with how optishot2 software reacts directly? I'm not actually looking for like super hard-core metrics. Just a fun time swinging a golf club. (Which is mostly how I see optishot2).

I'd just fire it all up and test how it feels right now, but my garage where my optishot hardware is is currently otherwise occupied...

...and the reason I am posting about this now is because optishot2 is basically end of life in 5 days and there will be no more course purchasing or online functionality (so I gotta decide if the course purchasing is worth it or if I can get by with replishot and tgc2019 at a... much cheaper entry point)

**Comment by zaren171** [comment]
I think it plays pretty similarly, and I've gotten good feedback on distances, etc. Replishot also gives swing path, face open/closed, etc. to try to match what the optishot provides.  The one caveat to how well replishot works is that tgc2019 needs to run smoothly.  For distance accuracy replishot controls the mouse and has to hold the mouse in certain positions for precise amounts of time, so if the game isn't running smoothly the time won't be precise and even feeding in the same shot's data multiple times will have vary different results.  If tgc2019 is running smoothly this won't be an issue.
